version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8000:5000
    volumes:
      - ./:/app

  pgsql:
    image: postgres:12
    environment:
      POSTGRES_USER: master_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master_service
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
    driver: local