version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: super_db
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/data/postgres

  engine:
    build:
      context: .
      dockerfile: engine.Dockerfile
    container_name: engine
    depends_on:
      - postgres
    environment:
      DATABASE_URI: "postgresql://super_admin:super_password@postgres:5432/super_db"
      WEB_URI: "tcp://web:5557"
    ports:
      - 5557:5557

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: web
    depends_on:
      - postgres
    environment:
      DATABASE_URI: "postgresql://super_admin:super_password@postgres:5432/super_db"
      ENGINE_URI: "tcp://0.0.0.0:5557"
    ports:
      - 8000:5000

volumes:
  postgres_db:
    driver: local
