[tool.poetry]
name = "roveit"
version = "0.1.0"
description = ""
authors = ["jmhayes3"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"
pyzmq = "^25.1.0"
praw = "^7.7.0"
sqlalchemy = "^2.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
