[tool.poetry]
name = "rbf"
version = "0.1.0"
description = "Reddit bot framework."
authors = ["jmhayes3 <22490346+jmhayes3@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
keywords = ["reddit", "bot"]
packages = [
    { include = "engine" },
    { include = "app" },
]
repository = "https://github.com/jmhayes3/rbf"

[tool.poetry.dependencies]
python = "^3.10"
pyzmq = "^25.0.2"
click = "^8.1.3"
flask = "^2.2.3"
python-dotenv = "^1.0.0"
sqlalchemy = "^2.0.9"
psycopg2 = "^2.9.6"
praw = "^7.7.0"
flask-sqlalchemy = "^3.0.3"
flask-login = "^0.6.2"
flask-wtf = "^1.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[tool.poetry.scripts]
rbf-engine = "console:cli"
rbf-app = "app:create_app().run()"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
